language: php

php:
  - 7.2.16

services:
  - postgresql

before_script:
  - psql -c 'create database shelter_test;' -U postgres
  - cp .env.travis .env
  -  composer self-update
  - composer install --no-interaction
  - npm install
  - npm run production
  - composer require encore/laravel-admin
  - php artisan vendor:publish --provider="Encore\Admin\AdminServiceProvider"
  - php artisan admin:install
  - php artisan migrate

#testing
script:
  - vendor/bin/phpunit  #--coverage-clover=coverage.xml
# codecov
# after_success:
#   - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
#   slack: iabs-brasilia:Fw9KR08fvWURvkuLnWWamoO0
#   on_success: never
#   on_fail: always