language: php

php:
  - 7.2.16

services:
  - postgresql

before_script:
  - psql -c 'create database shelter_test;' -U postgres
  - cp .env.travis .env
  - postgres #install and create db. ref to image
  -  composer self-update
  - composer install --no-interaction
  - npm install
  - npm run production

#testing
# script:
#   - vendor/bin/phpunit
# test:
#   adapter: postgresql
#   database: travis_ci_test

# notifications:
#   slack:
#     on_success: never
#     on_fail: always